name: sharecare_mobile
description: "ShareCare Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.0
  socket_io_client: ^2.0.3+1
  
  # Auth & Storage
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  
  # UI/UX
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lucide_icons: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
